##Importing Libraries

In [55]:
import pandas as pd 
import numpy as np
import seaborn as sns

##Reading the Dataset

In [56]:
dt=pd.read_csv("dataset_website.csv")
dt

index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0          1                          -1              1                   1   
1          2                           1              1                   1   
2          3                           1              0                   1   
3          4                           1              0                   1   
4          5                           1              0                  -1   
...      ...                         ...            ...                 ...   
11050  11051                           1             -1                   1   
11051  11052                          -1              1                   1   
11052  11053                           1             -1                   1   
11053  11054                          -1             -1                   1   
11054  11055                          -1             -1                   1   

       having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                     1                        -1             -1   
1                     1                         1             -1   
2                     1                         1             -1   
3                     1                         1             -1   
4                     1                         1             -1   
...                 ...                       ...            ...   
11050                -1                         1              1   
11051                -1                        -1             -1   
11052                 1                         1             -1   
11053                 1                         1             -1   
11054                 1                         1             -1   

       having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
0                     -1              -1                           -1  ...   
1                      0               1                           -1  ...   
2                     -1              -1                           -1  ...   
3                     -1              -1                            1  ...   
4                      1               1                           -1  ...   
...                  ...             ...                          ...  ...   
11050                  1               1                           -1  ...   
11051                  1              -1                           -1  ...   
11052                  1              -1                           -1  ...   
11053                 -1              -1                            1  ...   
11054                 -1              -1                            1  ...   

       popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0                1       1             -1         -1           -1         -1   
1                1       1             -1         -1            0         -1   
2                1       1              1         -1            1         -1   
3                1       1             -1         -1            1         -1   
4               -1       1             -1         -1            0         -1   
...            ...     ...            ...        ...          ...        ...   
11050           -1      -1              1          1           -1         -1   
11051           -1       1              1          1            1          1   
11052            1       1              1          1            1         -1   
11053           -1       1              1          1            1         -1   
11054            1       1             -1          1           -1         -1   

       Google_Index  Links_pointing_to_page  Statistical_report  Result  
0                 1                       1                  -1      -1  
1                 1                       1                   1      -1  
2                 1                       0                  -1      -1  
3                 1                      -1    

##Numerical Analysis

In [57]:
dt.head()
dt.shape

(11055, 32)

In [58]:
dt.size
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11055 entries, 0 to 11054
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   index                        11055 non-null  int64
 1   having_IPhaving_IP_Address   11055 non-null  int64
 2   URLURL_Length                11055 non-null  int64
 3   Shortining_Service           11055 non-null  int64
 4   having_At_Symbol             11055 non-null  int64
 5   double_slash_redirecting     11055 non-null  int64
 6   Prefix_Suffix                11055 non-null  int64
 7   having_Sub_Domain            11055 non-null  int64
 8   SSLfinal_State               11055 non-null  int64
 9   Domain_registeration_length  11055 non-null  int64
 10  Favicon                      11055 non-null  int64
 11  port                         11055 non-null  int64
 12  HTTPS_token                  11055 non-null  int64
 13  Request_URL                  11055 non-null  i

In [59]:
dt.describe()

index  having_IPhaving_IP_Address  URLURL_Length  \
count  11055.000000                11055.000000   11055.000000   
mean    5528.000000                    0.313795      -0.633198   
std     3191.447947                    0.949534       0.766095   
min        1.000000                   -1.000000      -1.000000   
25%     2764.500000                   -1.000000      -1.000000   
50%     5528.000000                    1.000000      -1.000000   
75%     8291.500000                    1.000000      -1.000000   
max    11055.000000                    1.000000       1.000000   

       Shortining_Service  having_At_Symbol  double_slash_redirecting  \
count        11055.000000      11055.000000              11055.000000   
mean             0.738761          0.700588                  0.741474   
std              0.673998          0.713598                  0.671011   
min             -1.000000         -1.000000                 -1.000000   
25%              1.000000          1.000000                  1.000000   
50%              1.000000          1.000000                  1.000000   
75%              1.000000          1.000000                  1.000000   
max              1.000000          1.000000                  1.000000   

       Prefix_Suffix  having_Sub_Domain  SSLfinal_State  \
count   11055.000000       11055.000000    11055.000000   
mean       -0.734962           0.063953        0.250927   
std         0.678139           0.817518        0.911892   
min        -1.000000          -1.000000       -1.000000   
25%        -1.000000          -1.000000       -1.000000   
50%        -1.000000           0.000000        1.000000   
75%        -1.000000           1.000000        1.000000   
max         1.000000           1.000000        1.000000   

       Domain_registeration_length  ...   popUpWidnow        Iframe  \
count                 11055.000000  ...  11055.000000  11055.000000   
mean                     -0.336771  ...      0.613388      0.816915   
std                       0.941629  ...      0.789818      0.576784   
min                      -1.000000  ...     -1.000000     -1.000000   
25%                      -1.000000  ...      1.000000      1.000000   
50%                      -1.000000  ...      1.000000      1.000000   
75%                       1.000000  ...      1.000000      1.000000   
max                       1.000000  ...      1.000000      1.000000   

       age_of_domain     DNSRecord   web_traffic     Page_Rank  Google_Index  \
count   11055.000000  11055.000000  11055.000000  11055.000000  11055.000000   
mean        0.061239      0.377114      0.287291     -0.483673      0.721574   
std         0.998168      0.926209      0.827733      0.875289      0.692369   
min        -1.000000     -1.000000     -1.000000     -1.000000     -1.000000   
25%        -1.000000     -1.000000      0.000000     -1.000000      1.000000   
50%         1.000000      1.000000      1.000000     -1.000000      1.000000   
75%         1.000000      1.000000      1.000000      1.000000      1.000000   
max         1.000000      1.000000      1.000000      1.000000      1.000000   

       Links_pointing_to_page  Statistical_report        Result  
count            11055.000000        11055.000000  11055.000000  
mean                 0.344007            0.719584      0.113885  
std                  0.569944            0.694437      0.993539  
min                 -1.000000           -1.000000     -1.000000  
25%                  0.000000            1.000000     -1.000000  
50%                  0.000000            1.000000      1.000000  
75%                  1.000000            1.000000      1.000000  
max                  1.000000            1.000000      1.000000  

[8 rows x 32 columns]

##Handling Null Values

In [60]:
dt.isnull().any()

index                          False
having_IPhaving_IP_Address     False
URLURL_Length                  False
Shortining_Service             False
having_At_Symbol               False
double_slash_redirecting       False
Prefix_Suffix                  False
having_Sub_Domain              False
SSLfinal_State                 False
Domain_registeration_length    False
Favicon                        False
port                           False
HTTPS_token                    False
Request_URL                    False
URL_of_Anchor                  False
Links_in_tags                  False
SFH                            False
Submitting_to_email            False
Abnormal_URL                   False
Redirect                       False
on_mouseover                   False
RightClick                     False
popUpWidnow                    False
Iframe                         False
age_of_domain                  False
DNSRecord                      False
web_traffic                    False
P

In [61]:
dt.isnull().sum()

index                          0
having_IPhaving_IP_Address     0
URLURL_Length                  0
Shortining_Service             0
having_At_Symbol               0
double_slash_redirecting       0
Prefix_Suffix                  0
having_Sub_Domain              0
SSLfinal_State                 0
Domain_registeration_length    0
Favicon                        0
port                           0
HTTPS_token                    0
Request_URL                    0
URL_of_Anchor                  0
Links_in_tags                  0
SFH                            0
Submitting_to_email            0
Abnormal_URL                   0
Redirect                       0
on_mouseover                   0
RightClick                     0
popUpWidnow                    0
Iframe                         0
age_of_domain                  0
DNSRecord                      0
web_traffic                    0
Page_Rank                      0
Google_Index                   0
Links_pointing_to_page         0
Statistica

##Splitting data into independent and dependent variables

In [62]:
x=dt.iloc[:,1:31].values
y=dt.iloc[:,-1].values
print(x)
print(y)

[[-1  1  1 ...  1  1 -1]
 [ 1  1  1 ...  1  1  1]
 [ 1  0  1 ...  1  0 -1]
 ...
 [ 1 -1  1 ...  1  0  1]
 [-1 -1  1 ...  1  1  1]
 [-1 -1  1 ... -1  1 -1]]
[-1 -1 -1 ... -1 -1 -1]


##Splitting data into train and test

In [63]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [64]:
x_train

array([[ 1, -1,  1, ...,  1,  1,  1],
       [ 1,  1,  1, ...,  1,  0,  1],
       [-1, -1,  1, ...,  1,  1, -1],
       ...,
       [-1,  1,  1, ...,  1,  1,  1],
       [-1, -1,  1, ...,  1,  1,  1],
       [ 1, -1,  1, ...,  1,  1,  1]])

In [65]:
y_train

array([ 1, -1, -1, ...,  1, -1, -1])

In [66]:
x_test

array([[ 1, -1,  1, ...,  1,  0,  1],
       [ 1, -1,  1, ...,  1,  0,  1],
       [ 1, -1,  1, ...,  1,  1,  1],
       ...,
       [-1, -1,  1, ...,  1,  1,  1],
       [ 1, -1,  1, ...,  1,  0,  1],
       [ 1, -1,  1, ...,  1,  1,  1]])

In [67]:
y_test

array([-1, -1, -1, ...,  1,  1,  1])

##Model Building

##1.Logistic Regression

In [68]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [69]:
y_pred1=lr.predict(x_test)
y_pred1

array([-1, -1,  1, ..., -1, -1,  1])

In [70]:
from sklearn.metrics import accuracy_score
log_reg=accuracy_score(y_test,y_pred1)
log_reg

0.9167797376752601

##2.Decision Tree

In [71]:
from sklearn.tree import DecisionTreeClassifier
dtr=DecisionTreeClassifier()
dtr.fit(x_train,y_train)

DecisionTreeClassifier()

In [73]:
y_pred2=dtr.predict(x_test)
y_pred2

array([-1, -1,  1, ...,  1,  1,  1])

In [74]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred2,y_test)

0.9647218453188603

##3.Random Forest Regression

In [75]:
from sklearn.ensemble import RandomForestClassifier
rfr=RandomForestClassifier()
rfr.fit(x_train,y_train)

RandomForestClassifier()

In [76]:
y_pred3=rfr.predict(x_test)
y_pred3

array([-1, -1,  1, ...,  1,  1,  1])

In [77]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred3,y_test)

0.9701492537313433

##4.Support Vector Machine

In [78]:
from sklearn.svm import SVC
svm=SVC()
svm.fit(x_train,y_train)

SVC()

In [79]:
y_pred4=svm.predict(x_test)
y_pred4

array([-1, -1,  1, ...,  1, -1,  1])

In [80]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred4,y_test)

0.9407507914970602

##5.K-Nearest Neighbors

In [81]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [82]:
y_pred5=knn.predict(x_test)
y_pred5

array([-1, -1, -1, ..., -1,  1,  1])

In [83]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred5,y_test)

0.9434644957033017

##Saving the model

In [84]:
import pickle
pickle.dump(rfr,open('phishing_website1.pk1','wb'))