##Importing Libraries

In [38]:
import pandas as pd 
import numpy as np
import seaborn as sns

##Reading the Dataset

In [1]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='U24I88Wbsnq2tTospRO3Pw1mLq_T-pt03Uj3X2Ac1V-9',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

bucket = 'webphishingdetectiondeployment-donotdelete-pr-fezfmcpyeo5wdz'
object_key = 'dataset_website.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

dt = pd.read_csv(body)
dt.head()


index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0      1                          -1              1                   1   
1      2                           1              1                   1   
2      3                           1              0                   1   
3      4                           1              0                   1   
4      5                           1              0                  -1   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                        -1             -1   
1                 1                         1             -1   
2                 1                         1             -1   
3                 1                         1             -1   
4                 1                         1             -1   

   having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
0                 -1              -1                           -1  ...   
1                  0               1                           -1  ...   
2                 -1              -1                           -1  ...   
3                 -1              -1                            1  ...   
4                  1               1                           -1  ...   

   popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0            1       1             -1         -1           -1         -1   
1            1       1             -1         -1            0         -1   
2            1       1              1         -1            1         -1   
3            1       1             -1         -1            1         -1   
4           -1       1             -1         -1            0         -1   

   Google_Index  Links_pointing_to_page  Statistical_report  Result  
0             1                       1                  -1      -1  
1             1                       1                   1      -1  
2             1                       0                  -1      -1  
3             1                      -1                   1      -1  
4             1                       1                   1       1  

[5 rows x 32 columns]

In [39]:
dt.head()
dt.shape

(11055, 32)

In [40]:
dt.size
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11055 entries, 0 to 11054
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   index                        11055 non-null  int64
 1   having_IPhaving_IP_Address   11055 non-null  int64
 2   URLURL_Length                11055 non-null  int64
 3   Shortining_Service           11055 non-null  int64
 4   having_At_Symbol             11055 non-null  int64
 5   double_slash_redirecting     11055 non-null  int64
 6   Prefix_Suffix                11055 non-null  int64
 7   having_Sub_Domain            11055 non-null  int64
 8   SSLfinal_State               11055 non-null  int64
 9   Domain_registeration_length  11055 non-null  int64
 10  Favicon                      11055 non-null  int64
 11  port                         11055 non-null  int64
 12  HTTPS_token                  11055 non-null  int64
 13  Request_URL                  11055 non-null  i

In [41]:
dt.describe()

index  having_IPhaving_IP_Address  URLURL_Length  \
count  11055.000000                11055.000000   11055.000000   
mean    5528.000000                    0.313795      -0.633198   
std     3191.447947                    0.949534       0.766095   
min        1.000000                   -1.000000      -1.000000   
25%     2764.500000                   -1.000000      -1.000000   
50%     5528.000000                    1.000000      -1.000000   
75%     8291.500000                    1.000000      -1.000000   
max    11055.000000                    1.000000       1.000000   

       Shortining_Service  having_At_Symbol  double_slash_redirecting  \
count        11055.000000      11055.000000              11055.000000   
mean             0.738761          0.700588                  0.741474   
std              0.673998          0.713598                  0.671011   
min             -1.000000         -1.000000                 -1.000000   
25%              1.000000          1.000000                  1.000000   
50%              1.000000          1.000000                  1.000000   
75%              1.000000          1.000000                  1.000000   
max              1.000000          1.000000                  1.000000   

       Prefix_Suffix  having_Sub_Domain  SSLfinal_State  \
count   11055.000000       11055.000000    11055.000000   
mean       -0.734962           0.063953        0.250927   
std         0.678139           0.817518        0.911892   
min        -1.000000          -1.000000       -1.000000   
25%        -1.000000          -1.000000       -1.000000   
50%        -1.000000           0.000000        1.000000   
75%        -1.000000           1.000000        1.000000   
max         1.000000           1.000000        1.000000   

       Domain_registeration_length  ...   popUpWidnow        Iframe  \
count                 11055.000000  ...  11055.000000  11055.000000   
mean                     -0.336771  ...      0.613388      0.816915   
std                       0.941629  ...      0.789818      0.576784   
min                      -1.000000  ...     -1.000000     -1.000000   
25%                      -1.000000  ...      1.000000      1.000000   
50%                      -1.000000  ...      1.000000      1.000000   
75%                       1.000000  ...      1.000000      1.000000   
max                       1.000000  ...      1.000000      1.000000   

       age_of_domain     DNSRecord   web_traffic     Page_Rank  Google_Index  \
count   11055.000000  11055.000000  11055.000000  11055.000000  11055.000000   
mean        0.061239      0.377114      0.287291     -0.483673      0.721574   
std         0.998168      0.926209      0.827733      0.875289      0.692369   
min        -1.000000     -1.000000     -1.000000     -1.000000     -1.000000   
25%        -1.000000     -1.000000      0.000000     -1.000000      1.000000   
50%         1.000000      1.000000      1.000000     -1.000000      1.000000   
75%         1.000000      1.000000      1.000000      1.000000      1.000000   
max         1.000000      1.000000      1.000000      1.000000      1.000000   

       Links_pointing_to_page  Statistical_report        Result  
count            11055.000000        11055.000000  11055.000000  
mean                 0.344007            0.719584      0.113885  
std                  0.569944            0.694437      0.993539  
min                 -1.000000           -1.000000     -1.000000  
25%                  0.000000            1.000000     -1.000000  
50%                  0.000000            1.000000      1.000000  
75%                  1.000000            1.000000      1.000000  
max                  1.000000            1.000000      1.000000  

[8 rows x 32 columns]

##Handling Null Values

In [42]:
dt.isnull().any()

index                          False
having_IPhaving_IP_Address     False
URLURL_Length                  False
Shortining_Service             False
having_At_Symbol               False
double_slash_redirecting       False
Prefix_Suffix                  False
having_Sub_Domain              False
SSLfinal_State                 False
Domain_registeration_length    False
Favicon                        False
port                           False
HTTPS_token                    False
Request_URL                    False
URL_of_Anchor                  False
Links_in_tags                  False
SFH                            False
Submitting_to_email            False
Abnormal_URL                   False
Redirect                       False
on_mouseover                   False
RightClick                     False
popUpWidnow                    False
Iframe                         False
age_of_domain                  False
DNSRecord                      False
web_traffic                    False
P

In [43]:
dt.isnull().sum()

index                          0
having_IPhaving_IP_Address     0
URLURL_Length                  0
Shortining_Service             0
having_At_Symbol               0
double_slash_redirecting       0
Prefix_Suffix                  0
having_Sub_Domain              0
SSLfinal_State                 0
Domain_registeration_length    0
Favicon                        0
port                           0
HTTPS_token                    0
Request_URL                    0
URL_of_Anchor                  0
Links_in_tags                  0
SFH                            0
Submitting_to_email            0
Abnormal_URL                   0
Redirect                       0
on_mouseover                   0
RightClick                     0
popUpWidnow                    0
Iframe                         0
age_of_domain                  0
DNSRecord                      0
web_traffic                    0
Page_Rank                      0
Google_Index                   0
Links_pointing_to_page         0
Statistica

##Splitting data into independent and dependent variables

In [44]:
x=dt.iloc[:,1:31].values
y=dt.iloc[:,-1].values
print(x)
print(y)

[[-1  1  1 ...  1  1 -1]
 [ 1  1  1 ...  1  1  1]
 [ 1  0  1 ...  1  0 -1]
 ...
 [ 1 -1  1 ...  1  0  1]
 [-1 -1  1 ...  1  1  1]
 [-1 -1  1 ... -1  1 -1]]
[-1 -1 -1 ... -1 -1 -1]


##Splitting data into train and test

In [45]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [46]:
x_train

array([[ 1, -1,  1, ...,  1,  1,  1],
       [ 1,  1,  1, ...,  1,  0,  1],
       [-1, -1,  1, ...,  1,  1, -1],
       ...,
       [-1,  1,  1, ...,  1,  1,  1],
       [-1, -1,  1, ...,  1,  1,  1],
       [ 1, -1,  1, ...,  1,  1,  1]])

In [47]:
y_train

array([ 1, -1, -1, ...,  1, -1, -1])

In [48]:
x_test

array([[ 1, -1,  1, ...,  1,  0,  1],
       [ 1, -1,  1, ...,  1,  0,  1],
       [ 1, -1,  1, ...,  1,  1,  1],
       ...,
       [-1, -1,  1, ...,  1,  1,  1],
       [ 1, -1,  1, ...,  1,  0,  1],
       [ 1, -1,  1, ...,  1,  1,  1]])

In [49]:
y_test

array([-1, -1, -1, ...,  1,  1,  1])

##Model Building

##1.Logistic Regression

In [50]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [51]:
y_pred1=lr.predict(x_test)
y_pred1

array([-1, -1,  1, ..., -1, -1,  1])

In [52]:
from sklearn.metrics import accuracy_score
log_reg=accuracy_score(y_test,y_pred1)
log_reg

0.9167797376752601

##2.Decision Tree

In [53]:
from sklearn.tree import DecisionTreeClassifier
dtr=DecisionTreeClassifier()
dtr.fit(x_train,y_train)

DecisionTreeClassifier()

In [54]:
y_pred2=dtr.predict(x_test)
y_pred2

array([-1, -1,  1, ...,  1,  1,  1])

In [55]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred2,y_test)

0.9633649932157394

##3.Random Forest Regression

In [56]:
from sklearn.ensemble import RandomForestClassifier
rfr=RandomForestClassifier()
rfr.fit(x_train,y_train)

RandomForestClassifier()

In [57]:
y_pred3=rfr.predict(x_test)
y_pred3

array([-1, -1,  1, ...,  1,  1,  1])

In [58]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred3,y_test)

0.9692446856625961

##4.Support Vector Machine

In [59]:
from sklearn.svm import SVC
svm=SVC()
svm.fit(x_train,y_train)

SVC()

In [60]:
y_pred4=svm.predict(x_test)
y_pred4

array([-1, -1,  1, ...,  1, -1,  1])

In [62]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred4,y_test)

0.9407507914970602

##5.K-Nearest Neighbors

In [63]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [64]:
y_pred5=knn.predict(x_test)
y_pred5

array([-1, -1, -1, ..., -1,  1,  1])

In [65]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred5,y_test)

0.9434644957033017

##Saving the model

In [66]:
import pickle
pickle.dump(rfr,open('phishing_website1.pk1','wb'))

In [4]:
!pip install -U ibm-watson-machine-learning

In [7]:
from ibm_watson_machine_learning import APIClient
import json
wml_credentials = {

"apikey":"_zDJNAYr2H1KB0sBQR3kFuvmagUppIsgETK_9OyZrPRu",

"url":"https://us-south.ml.cloud.ibm.com"

}
wml_client =APIClient(wml_credentials)

In [17]:
def guid_from_space_name(client, space_name):
    space = client.spaces.get_details()
    #print(space)
    return(next(item for item in space['resources'] if item['entity']["name"] == space_name)['metadata']['id'])

In [19]:
space_uid = guid_from_space_name(wml_client, 'model')
print("Space UID =" + space_uid)

Space UID =ee52bb72-fc22-4445-9c35-217fba76be2f


In [21]:
wml_client.set.default_space(space_uid)

'SUCCESS'

In [22]:
wml_client.software_specifications.list()

-----------------------------  ------------------------------------  ----
NAME                           ASSET_ID                              TYPE
default_py3.6                  0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base
kernel-spark3.2-scala2.12      020d69ce-7ac1-5e68-ac1a-31189867356a  base
pytorch-onnx_1.3-py3.7-edt     069ea134-3346-5748-b513-49120e15d288  base
scikit-learn_0.20-py3.6        09c5a1d0-9c1e-4473-a344-eb7b665ff687  base
spark-mllib_3.0-scala_2.12     09f4cff0-90a7-5899-b9ed-1ef348aebdee  base
pytorch-onnx_rt22.1-py3.9      0b848dd4-e681-5599-be41-b5f6fccc6471  base
ai-function_0.1-py3.6          0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda  base
shiny-r3.6                     0e6e79df-875e-4f24-8ae9-62dcc2148306  base
tensorflow_2.4-py3.7-horovod   1092590a-307d-563d-9b62-4eb7d64b3f22  base
pytorch_1.1-py3.6              10ac12d6-6b30-4ccd-8392-3e922c096a92  base
tensorflow_1.15-py3.6-ddl      111e41b3-de2d-5422-a4d6-bf776828c4b7  base
autoai-kb_rt22.2-py3.10        125b6d9

In [70]:
software_spec_uid= wml_client.software_specifications.get_id_by_name('default_py3.7')
software_spec_uid

'e4429883-c883-42b6-87a8-f419d64088cd'

In [72]:
import sklearn 
sklearn.__version__

'1.0.2'

In [74]:
MODEL_NAME = 'Web Phishing Detection' 
DEPLOYMENT_NAME = 'webphishing' 
DEMO_MODEL = rfr

In [75]:
software_spec_uid= wml_client.software_specifications.get_id_by_name('runtime-22.1-py3.9')

In [76]:
model_props = {
    wml_client.repository.ModelMetaNames.NAME: MODEL_NAME, 
    wml_client.repository.ModelMetaNames.TYPE: 'scikit-learn_1.0', 
    wml_client.repository.ModelMetaNames.SOFTWARE_SPEC_UID: software_spec_uid 
}

In [79]:
model_details = wml_client.repository.store_model(
    model=DEMO_MODEL, 
    meta_props=model_props, 
    training_data=x_train, 
    training_target=y_train
)

In [81]:
model_details

{'entity': {'hybrid_pipeline_software_specs': [],
  'label_column': 'l1',
  'schemas': {'input': [{'fields': [{'name': 'f0', 'type': 'int'},
      {'name': 'f1', 'type': 'int'},
      {'name': 'f2', 'type': 'int'},
      {'name': 'f3', 'type': 'int'},
      {'name': 'f4', 'type': 'int'},
      {'name': 'f5', 'type': 'int'},
      {'name': 'f6', 'type': 'int'},
      {'name': 'f7', 'type': 'int'},
      {'name': 'f8', 'type': 'int'},
      {'name': 'f9', 'type': 'int'},
      {'name': 'f10', 'type': 'int'},
      {'name': 'f11', 'type': 'int'},
      {'name': 'f12', 'type': 'int'},
      {'name': 'f13', 'type': 'int'},
      {'name': 'f14', 'type': 'int'},
      {'name': 'f15', 'type': 'int'},
      {'name': 'f16', 'type': 'int'},
      {'name': 'f17', 'type': 'int'},
      {'name': 'f18', 'type': 'int'},
      {'name': 'f19', 'type': 'int'},
      {'name': 'f20', 'type': 'int'},
      {'name': 'f21', 'type': 'int'},
      {'name': 'f22', 'type': 'int'},
      {'name': 'f23', 'type': 'i

In [82]:
model_id = wml_client.repository.get_model_id(model_details)
model_id

'6b41accc-1503-461d-a118-6c82ed873020'

In [83]:
deployment_props = {
    wml_client.deployments.ConfigurationMetaNames.NAME:DEPLOYMENT_NAME, 
    wml_client.deployments.ConfigurationMetaNames.ONLINE: {}
}

In [84]:
deployment = wml_client.deployments.create(
    artifact_uid=model_id, 
    meta_props=deployment_props 
)



#######################################################################################

Synchronous deployment creation for uid: '6b41accc-1503-461d-a118-6c82ed873020' started

#######################################################################################


initializing
Note: online_url is deprecated and will be removed in a future release. Use serving_urls instead.

ready


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='8e534a05-eedf-48ee-9287-3f71e1bc60ec'
------------------------------------------------------------------------------------------------


